WITH RentalCounts AS (
    SELECT CAR_ID, COUNT(*) as cnt
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING cnt >= 5
)

SELECT MONTH(START_DATE) as MONTH, A.CAR_ID, COUNT(*) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as A
JOIN RentalCounts as B
ON A.CAR_ID = B.CAR_ID
WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY MONTH(START_DATE), A.CAR_ID
ORDER BY MONTH ASC, A.CAR_ID DESC;