-- 코드를 입력하세요
SELECT b.CATEGORY, SUM(s.SALES) as TOTAL_SALES
FROM BOOK b join BOOK_SALES s
ON b.BOOK_ID = s.BOOK_ID
WHERE YEAR(s.SALES_DATE) = '2022' and MONTH(s.SALES_DATE) = '01'
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;