-- 코드를 작성해주세요
WITH YEAR_DEV_INFO AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR, (YDI.MAX_SIZE - ED.SIZE_OF_COLONY) AS YEAR_DEV, ED.ID
FROM ECOLI_DATA AS ED
LEFT JOIN YEAR_DEV_INFO YDI
ON YEAR(ED.DIFFERENTIATION_DATE) = YDI.YEAR
ORDER BY YEAR(ED.DIFFERENTIATION_DATE) ASC, YEAR_DEV ASC;
