-- 코드를 작성해주세요
WITH FISH_MAX AS (
    SELECT FISH_TYPE, MAX(LENGTH) as MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT I.ID, N.FISH_NAME, M.MAX_LENGTH AS LENGTH
FROM FISH_MAX AS M
LEFT JOIN FISH_INFO AS I
ON M.FISH_TYPE = I.FISH_TYPE AND I.LENGTH = M.MAX_LENGTH
LEFT JOIN
FISH_NAME_INFO N
ON N.FISH_TYPE = M.FISH_TYPE
ORDER BY I.ID;
